#!/bin/sh

case $1 in
-f) force=true; shift ;;
esac

patch=$(expr substr $1 1 20)
( cd ~/packages/git-repos/gridengine; git log -p $patch^..$patch >/tmp/patch )
sed -i '/^diff --git .*Changelog$/,/^diff/d' /tmp/patch
if [ "$force" = true ]; then
    patch -t -p1 </tmp/patch
else
    patch -p1 --dry-run </tmp/patch &&
    patch -p1 </tmp/patch &&
    darcs record -a --look-for-adds
fi
